Not just for disks anymore.  Anything to do with dust scattering and extinction in Orion. 

* Evidence for dust distribution inside proplyds

** Dust shells
+ See Fig 7c of Bally:2000a (also fig 4b)
+ The best examples are 206-447 and 197-427
  + These show an inner disk, then a gap, then an extinction shell


** Filaments
+ In other sources there is evidence for filaments inside the envelope of the ionization front
+ Maybe these are remnants of the cloud filaments that fed the accretion disk
+ Maybe they still have inflow?
+ The best case is probably the giant proplyd 244-440 (see MUSE data)
+ But also see 180-331 and maybe 141-301

* No evidence for a translucent disk in the Orion Nebula
+ Disk 218-354
** Comparison with giant silhouette

*** Loophole in the Miotello paper
+ Nebular background has a gradient across the disk, but they didn't take account of this
+ This casts doubt on their measurements for the translucent portions

#+BEGIN_SRC python :results file
  import numpy as np
  import matplotlib.pyplot as plt
  for pos in ["east", "center", "west"]:
      x, y = np.loadtxt("114426-major-{}.dat".format(pos), unpack=True)
      plt.plot(x, y, label=pos)
  plt.ylim(0.0, None)
  plt.legend()
  plotfile = "114426-major-cuts.pdf"
  plt.savefig(plotfile)
  return plotfile
#+END_SRC

#+RESULTS:
[[file:114426-major-cuts.pdf]]

** Plotting cut profiles

#+BEGIN_SRC python :results file :tangle shadow-profiles.py
  import numpy as np
  import matplotlib.pyplot as plt
  pixscale = {"acs": 0.0500016812098, "wfpc2": 0.0455214603946}
  yscale = {"acs": 34.0, "wfpc2": 0.49}
  
  ao_data_radius = np.linspace(0.01, 1.04, 20)
  ao_data_major = np.array([
      0.06, 0.24, 0.39, 0.47, 0.56, 0.63, 0.67, 0.71, 0.74, 0.78, 0.83, 0.88, 0.91, 0.94, 0.98, 0.97, 0.98, 0.99, 1.00, 1.01
  ])
  ao_std_major = np.array([
      0.0, 0.145, 0.12, 0.09, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00
  ])
  ao_data_minor = np.array([
      0.075, 0.26, 0.42, 0.52, 0.65, 0.73, 0.82, 0.88, 0.92, 0.97, 0.97, 0.98, 0.985, 0.985, 1.00, 1.02, 1.01, 1.00, 1.00, 1.01
  ])
  
  def get_xydata(s):
      x, y = np.loadtxt("{}-wcs.dat".format(s), unpack=True)
      return pixscale[camera]*(x - x0), y/yscale[camera]
  
  NR = 41
  rgrid = pixscale["acs"]*np.arange(NR) 
  ymajor_list_grid = []
  for i in range(NR):
      ymajor_list_grid.append(list())
  yminor_list_grid = []
  for i in range(NR):
      yminor_list_grid.append(list())
  
  fig = plt.figure(figsize=(8,8))
  fig.add_subplot(211)
  camera = "acs"
  for id_, x0 in [
          ["major-B06",  41.0], 
          ["major-R00L", 41.0], 
          ["major-R05L", 41.5], 
  ]:
      x, y = get_xydata(id_)
      print
      print camera, id_
  
      plt.bar(x, y, width=pixscale[camera], lw=0.0, color="k", align="center", alpha=0.1)
      plt.bar(x, 0.05*y, width=pixscale[camera], lw=0.0, color="k", align="center", alpha=0.2)
      if "B06" in id_:
          # Fit polynomial to BG sections
          m = (x < -1.0) | (x > 0.8)
          fit_major = np.poly1d(np.polyfit(x[m], y[m], 3))
          plt.plot(x, fit_major(x), color="k", alpha=0.5, lw=1)
      # Add into radial grid (always using ACS pixel size)
      for i, j in enumerate(abs(x/pixscale["acs"]).astype(int)):
          # save normalized brightness in a box according to the radius
          bright = y[i]/fit_major(x[i])
          print j, bright
          if j < NR:
              ymajor_list_grid[j].append(bright)
  
  # Calculate statistics for major axis
  ymajor_mean_grid = np.empty((NR,))
  ymajor_std_grid = np.empty((NR,))
  for j, ylist in enumerate(ymajor_list_grid):
      ymajor_mean_grid[j] = np.mean(ylist)
      ymajor_std_grid[j] = np.std(ylist)
  
  
  camera = "wfpc2"
  for id_, x0 in [
          ["major-wfpc2-R39", 44.0], 
  ]:
      x, y = get_xydata(id_)
      plt.plot(x, y, color="r", alpha=0.3)
      plt.plot(x, 0.05*y, color="r", alpha=0.6)
  
  # Don't plot the flanking major profiles any more
  # camera = "acs"
  # for id_, x0 in [
  #         ["major-top-R05L",  41.5], 
  #         ["major-bot-R05L",  41.5], 
  # ]:
  #     x, y = get_xydata(id_)
  #     plt.plot(x, y, color="k", alpha=0.3)
  
  plt.text(-1.9, 1.25, "M42 218-354: major axis cuts")
  plt.text(1.5, 0.1, "x 0.05")
  plt.text(1.5, 1.1, "x 1.00")
  plt.xlim(-2.0, 2.0)
  plt.ylim(0.0, 1.4)
  plt.grid(ls="-", alpha=0.3)
  plt.ylabel("Surface brightness")
  
  fig.add_subplot(212)
  camera = "acs"
  for id_, x0 in [
          ["minor-star-B06",  42.0], 
          ["minor-star-R00L", 41.0], 
          ["minor-star-R05L",  41.5], 
  ]:
      x, y = get_xydata(id_)
      # plt.plot(x, y, label=id_, drawstyle="steps-mid")
      plt.bar(x, y, width=pixscale[camera], lw=0.0, color="k", align="center", alpha=0.1)
      plt.bar(x, 0.05*y, width=pixscale[camera], lw=0.0, color="k", align="center", alpha=0.2)
      if "B06" in id_:
          # Fit polynomial to BG sections
          m = (x < -0.5) | (x > 0.5)
          fit_minor = np.poly1d(np.polyfit(x[m], y[m], 3))
          plt.plot(x, fit_minor(x), color="k", alpha=0.5, lw=1.5)
        # Add into radial grid (always using ACS pixel size)
      for i, j in enumerate(abs(x/pixscale["acs"]).astype(int)):
          # save normalized brightness in a box according to the radius
          bright = y[i]/fit_minor(x[i])
          print j, bright
          if j < NR:
              yminor_list_grid[j].append(bright)
  
  # Calculate statistics for minor axis
  yminor_mean_grid = np.empty((NR,))
  yminor_std_grid = np.empty((NR,))
  for j, ylist in enumerate(yminor_list_grid):
      yminor_mean_grid[j] = np.mean(ylist)
      yminor_std_grid[j] = np.std(ylist)
  
  camera = "wfpc2"
  for id_, x0 in [
          ["minor-wfpc2-R39", 45.5], 
  ]:
      x, y = get_xydata(id_)
      plt.plot(x, y, color="r", alpha=0.3)
      plt.plot(x, 0.05*y, color="r", alpha=0.6)
  
  plt.text(-1.9, 1.25, "M42 218-354: minor axis cuts")
  plt.text(1.5, 0.1, "x 0.05")
  plt.text(1.5, 1.1, "x 1.00")
  plt.xlim(-2.0, 2.0)
  plt.ylim(0.0, 1.4)
  plt.grid(ls="-", alpha=0.3)
  plt.ylabel("Surface brightness")
  
  
  figfile = "profiles-acs-218-354.pdf"
  plt.xlabel("Offset, arcsec")
  plt.legend()
  fig.tight_layout()
  plt.savefig(figfile)
  
  figfile = "cprofiles-acs-218-354.pdf"
  cfig = plt.figure(figsize=(8,5))
  ymax = 2.4  
  
  camera = "acs"
  for id_, x0, extra_scale, c, lab in [
          ["major-R00L",       41.0, 1.0,  "k", "H alpha"], 
          ["major-F435W-R00L", 41.0, 0.36, "b", "B continuum"], 
          ["major-F555W-R00L", 41.0, 0.95, "g", "V continuum"], 
          ["major-F775W-R00L", 41.0, 0.47, "r", "I continuum"], 
  ]:
      x, y = get_xydata(id_)
      # plt.plot(x, y, label=id_, drawstyle="steps-mid")
      plt.plot(x, y/extra_scale, c, alpha=0.7, label=lab)
  
  plt.xlim(-2.0, 2.0)
  plt.ylim(0.0, ymax)
  plt.grid(ls="-", alpha=0.3)
  plt.ylabel("Surface brightness")
  plt.xlabel("Offset, arcsec")
  plt.legend(fontsize="small", title="Filter", loc="upper left")
  fig.tight_layout()
  plt.savefig(figfile)
  
  
  
  figfile = "rprofiles-acs-218-354.pdf"
  rfig = plt.figure(figsize=(8,8))
  ymax = 1.4  
  
  rfig.add_subplot(211)
  plt.fill_betweenx([0.0, ymax], [0.34, 0.34], color="k", alpha=0.1) 
  m = ymajor_std_grid < 0.5
  p3, _, _ = plt.errorbar(ao_data_radius, ao_data_major, ao_std_major, fmt='bo')
  p1, _, _ = plt.errorbar(rgrid[m], ymajor_mean_grid[m], ymajor_std_grid[m], fmt='ro')
  # Add in WFPC2 as function of radius
  camera = "wfpc2"
  for id_, x0 in [
          ["major-wfpc2-R39", 44.0], 
  ]:
      x, y = get_xydata(id_)
      p2, = plt.plot(np.abs(x), y/fit_major(x), color="g", alpha=0.3)
  # finish WFPC2
  plt.xlim(0.0, 1.4)
  plt.ylim(0.0, ymax)
  plt.grid(ls="-", alpha=0.3)
  plt.legend([p1, p2, p3], ["HST-ACS", "HST-WFPC2", "Magellan AO"], loc="center right", title="Major axis", fancybox=True, shadow=True)
  plt.ylabel("Mean brightness profile")
  
  rfig.add_subplot(212)
  plt.fill_betweenx([0.0, ymax], [0.28, 0.28], color="k", alpha=0.1) 
  m = yminor_std_grid < 10.0
  p3, = plt.plot(ao_data_radius, ao_data_minor, 'bo')
  p1, _, _ = plt.errorbar(rgrid[m], yminor_mean_grid[m], yminor_std_grid[m], fmt='ro')
  # Add in WFPC2 as function of radius
  camera = "wfpc2"
  for id_, x0 in [
          ["minor-wfpc2-R39", 45.5], 
  ]:
      x, y = get_xydata(id_)
      p2, = plt.plot(np.abs(x), y/fit_minor(x), color="g", alpha=0.3)
  # finish WFPC2
  plt.xlim(0.0, 1.4)
  plt.ylim(0.0, ymax)
  plt.grid(ls="-", alpha=0.3)
  plt.legend([p1, p2, p3], ["HST-ACS", "HST-WFPC2", "Magellan AO"], loc="center right", title="Minor axis", fancybox=True, shadow=True)
  plt.xlabel("Radius, arcsec")
  plt.ylabel("Mean brightness profile")
  
  rfig.tight_layout()
  plt.savefig(figfile)
  
  return figfile
#+END_SRC

#+RESULTS:
[[file:rprofiles-acs-218-354.pdf]]

** Alignment of images

+ We center on the unsaturated star 219-355 just SE of the disk
  + The 2 Robberto (GO 10246) images are well-aligned
  + but the Bally (GO 9825) image is slightly off and needs shifting by about 1 arcsec


*** Calculation of the offset that should be applied to Bally
The apparent coordinates of the star in the different images are
|          |          RA |         Dec |      xpix |      ypix |  bright |
|----------+-------------+-------------+-----------+-----------+---------|
| Bally    | 5:35:21.795 | -5:23:55.40 | 3219.1345 | 5948.9333 | 95.0683 |
| Robberto | 5:35:21.878 | -5:23:55.48 | 7124.8684 | 4200.3029 | 55.6008 |
Note that the star seems to be variable, but that doesn't matter

So we can calculate the offset like this:
|               | Bally          | Robberto       | Diff         | arcsec |
|---------------+----------------+----------------+--------------+--------|
| RA (hms)      | 5@ 35' 21.795" | 5@ 35' 21.878" | 0@ 0' 0.083" |  1.239 |
| Dec (deg ' ") | -5@ 23' 55.40" | -5@ 23' 55.48" | -0@ 0' 0.08" | -0.080 |
#+TBLFM: @2$4=$3 - $2::@3$4=-($2 - $3)::@3$5=3600 deg($4);f3::@2$5=3600 14.93 deg($4);f3

In other words: (1.239, -0.080) arcsec.

**** In practise I aligned the images in DS9 like this:
#+BEGIN_SRC sh
# Robberto Strip 0L
xpaget ds9 file
# -> hlsp_orion_hst_acs_strip0l_f658n_v1_drz.fits[SCI]
xpaset -p ds9 pan to 5:35:21.878 -5:23:55.48 wcs fk5
# Bally
xpaset -p ds9 frame next
xpaget ds9 file
# -> j8oc06010_drz.fits[SCI]
xpaset -p ds9 pan to 5:35:21.795 -5:23:55.40 wcs fk5
# Robberto Strip 5L
xpaset -p ds9 frame next
xpaget ds9 file
# -> hlsp_orion_hst_acs_strip5l_f658n_v1_drz.fits[SCI]
xpaset -p ds9 pan to 5:35:21.878 -5:23:55.48 wcs fk5
#+END_SRC


**** The WFPC2 image

+ This has =CD1_1 = -1.26448501095961E-05= => 0.0455214603946 arcsec
+ whereas the ACS images have =CD1_1 = -1.388935589155969E-05= => 0.0500016812098 arcsec
** Templates to remove the saturated PSF
This star looks very similar
+ 5:35:00.103 -5:23:02.11 - 001-302
+ But it is binary
This one might be better
+ 5:34:57.732 -5:23:52.72 - 577-352
* PSF blurring of an opaque disk
** DONE Install tinytim software
CLOSED: [2013-12-30 Mon 22:57]
[[file:tinytim/src/tinytim-7.5/][file:~/Dropbox/OrionDust/tinytim/src/tinytim-7.5/]]
** Use tinytim to model an opaque disk
+ use the /scene/ capabilities of =tinytim3=
  + this takes a model image and distorts it and convolves with the PSF
  + suitable for comparison with the =_flt.fits= files
** Find the positions on the ACS chip of the object
+ [X] I have requested the relevant datasets
+ [ ] Download datasets
+ [ ] Find positions

* DONE STIS observations of 218-354
CLOSED: [2013-12-30 Mon 23:01]
:LOGBOOK:
CLOCK: [2013-12-22 Sun 12:26]--[2013-12-22 Sun 12:40] =>  0:14
CLOCK: [2013-12-22 Sun 11:48]--[2013-12-22 Sun 12:26] =>  0:38
CLOCK: [2013-12-19 Thu 18:20]--[2013-12-19 Thu 19:17] =>  0:57
:END:
+ Low resolution spectra of 218-354 from [[file:~/Work/HST-STIS/McCollum9866/][McCollum GO9866]]
  + o8t502010_sx2.fits
+ Includes
  + H\alpha + [N II] 6563,48,84
  + [S III] 9531 - looks like extinction is much weaker here
+ In principle we can remove the continuum pretty well
  + Assume stellar profile is separable: F(\lambda) \cdot G(x)
  + First subtract nebula from star profile - take slice as close as possible above and below
    + This gives F(\lambda) by taking the center of the star trace
  + Then find G(x) by summing over \lambda ranges where there are no strong lines
  + Finally, we subtract F(\lambda) \cdot G(x) to get the pure nebula+disk spectrum

#+BEGIN_SRC sh
xpaset -p ds9 fits /Users/will/Work/HST-STIS/McCollum9866/o8t502010_sx2.fits
#+END_SRC

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-sub-star.fits
#+END_SRC

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-H_alpha.fits
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-H_alpha-nc.fits
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-H_alpha-cont.fits
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-S_III_9531-nc.fits
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-S_III_9531-cont.fits
#+END_SRC

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-S_III_9531.fits
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-S_III_9069-nc.fits
#+END_SRC
#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-S_III_9069-cont.fits
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-S_III_9069.fits
#+END_SRC

#+RESULTS:

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-Ar_III_7136-nc.fits
#+END_SRC

#+BEGIN_SRC sh
xpaset -p ds9 fits $PWD/stis-218-354-He_I_5876-nc.fits
#+END_SRC


#+RESULTS:


* Comparing shadow disks with shadow globules

+ Studies like Miotello claim to show increasingly large grains at higher optical depth
+ But there are questions about the effects of diffuse transmission through the disk
+ One way of addressing this would be with a comparitive study of
  1. The translucent parts of the slhouette disks
  2. Translucent foreground clouds and globules in the Veil
     + The SW cloud
     + The cloud to the E of LP Ori
     + The Dark Bay
     + Other small clouds
+ We have excellent wavelength coverage from U (3360 A) to I (8500 A) of all these regions with WFPC2 and ACS
+ Plus ground-based images from U to I with WFI, and JHK with ISPI
+ And finally NICMOS observations at 1.1 and 1.6 microns (JH), but this has very spotty coverage
  + Visit 49 would have been great for SW cloud but it was lost from pointing error
  + Visits 24, 25, 26 cover Dark Bay
  + Visits 48, 47 cover some clouds to NW of LL Ori
  + Visits 28, 29 cover some clouds in N of nebula
** Plan of what to do 
+ Take all the ACS images of the SW cloud and calculate A_{\lambda} = -2.5 log(S_{\lambda}/S_{0}) where S_{0} is the interpolated BG value
+ Plot A_{B} vs A_{V} etc
+ Compare with predictions of different extinction laws
+ Look for non-linearity
+ Compensate for a constant FG value
+ Then do the same for the shadow disks

** Fixing up the WCS in the C(Hb) map
:LOGBOOK:
CLOCK: [2013-09-05 Thu 10:00]--[2013-09-05 Thu 12:34] =>  2:34
:END:

+ Peg th1C to the coordinates in the Robberto ACS images
#+BEGIN_SRC python :results output
import astropy.io.fits as pyfits
f = pyfits.open("/Users/will/Work/BobPC/2005/chbeta-fix.fits")

hdr = f[0].header

# Convert to degrees
for k in ["CD1_1", "CD1_2", "CD2_1", "CD2_2"]:
    hdr[k] /= 3600.0
    if k.endswith("1"):
        hdr[k] *= -1.0
# Put in coords of th1C
hdr.update(ctype1="RA---TAN", ctype2="DEC--TAN", crpix1=389.4, crpix2=577.0, crval1=83.818547, crval2=-5.3897231)
f.writeto("chbeta-radec.fits", clobber=True)

#+END_SRC
 
#+RESULTS:
: WARNING: Overwriting existing file 'chbeta-radec.fits'. [astropy.io.fits.hdu.hdulist]

** An east-west cut across the southwest cloud
#+BEGIN_SRC python :results file
import numpy as np
import matplotlib.pyplot as plt
pixscale = {"acs": 0.0500016812098, "wfpc2": 0.0455214603946}

def get_xydata(camera, filter):
    x, y = np.loadtxt("swcloud-{}-{}.dat".format(camera, filter), unpack=True)
    return pixscale[camera]*x, y

filters = ["V", "B", "Ha", "i", "z"]

A = {}
for filt in filters:
    x, y = get_xydata("acs", filt)
    mleft = (x > 60.0) & (x < 70.0)
    mright = (x > 130.0)
    m = mleft | mright
    p = np.poly1d(np.polyfit(x[m], y[m], 2))
    A[filt] = -2.5*np.log10(y/p(x))
    msw = (x > 60.0) & (x < 150.0)
    plt.plot(A["V"], A[filt]/A["V"], ".", alpha=0.2, label=filt)

plt.ylim(-0.1, 1.1)
plt.xlabel("A_V")
plt.ylabel("A_lambda / A_V")
plt.legend(loc="upper left")
plt.grid(alpha=0.3)

figname = "swcloud-cuts-acs.pdf"
plt.savefig(figname)
return figname
#+END_SRC

#+RESULTS:
[[file:swcloud-cuts-acs.pdf]]

+ We graph A_{\lambda}/A_{V} as function of A_{V}
  + a lot of noise at A_{V}  < 0.2, as you would expect due to uncertainties in the nebular bg (and fluctuations)
  + more or less flat part extending from A_{V} = 0.5 to 1.5
    + This is what we expect for constant dust properties and no scattering
    + Some filters show multiple strands in range 0.5 to 1
    + Average values around A_{V} = 1.2
      | Filter |    \lambda |  1/\lambda | A_{\lambda}/A_{V} |
      |--------+------+------+-------|
      | B      | 4350 | 2.30 |  0.76 |
      | V      | 5550 | 1.80 |   1.0 |
      | H\alpha     | 6580 | 1.52 |   0.9 |
      | i      | 7750 | 1.29 |   0.7 |
      | z      | 8500 | 1.18 |  0.63 |
      #+TBLFM: $3=10000/$2 ; f2
    + This extinction curve is very similar to what Miotello find for their pixel A, which is one where they say the grains are 0.6 microns
    + Except that our peak in the V-band is a bit narrower


+ tendency to go up from A_{V} = 1.5 to 2
* Reflection nebulae in M42
There are several areas of reflection nebulosity:
+ Cavity around LP Ori
+ Bright Blue Star to the SW
  + This looks great - more or less circular, but with wisps
  + Reminiscent of the Pleiades
+ The Bright Bar, in particular the SW end
+ The gray wisps:
  + The ones between the Trapezium and LL2
  + The ones to SE of L Ori
  + The ones in the far S
+ The steely blue-gray shell
  + The rippling wing to the SE
  + The NW wing
+ The gray globules to the far W
* The dark tadpole 4572-337
:LOGBOOK:
CLOCK: [2013-09-13 Fri 10:23]--[2013-09-18 Wed 23:39] => 133:16
:END:
:PROPERTIES:
:EXPORT_FILE_NAME: DarkTadpole/ghost-globule
:END:
[[file:DarkTadpole/]]
+ Looks like a giant proplyd
+ But seen in absorption
+ And with a shocked shell too
+ Position is =5:34:57.199 -5:23:37.49=
  + According to Robberto images
  + So OW name should be 4572-337
+ [2013-09-16 Mon] New name: Ghost Globule


** Limits on possible emission
+ Looking at cuts across the head, it is possible that there is some Ha emission, but it must be at a very low level.
  + Less than 0.05 in the Bally images
  + BG is 2.7 ish
** Depth of absorption
+ BG level (samples near head): 2.74 +/- 0.03, 2.73 +/- 0.03
  + vmeane([2.74 +/- 0.03, 2.73 +/- 0.03]) = 2.735 +/- 0.02
+ Core: 2.35
+ Head: 2.52 +/- 0.03
+ Tail filaments:
  + I: 2.64 +/ 0.02
    + BG = vmeane([2.74 +/- 0.03, 2.80 +/- 0.02]) = 2.78 +/- 0.02
  + II: 2.84 +/- 0.03
    + BG = vmeane([2.99 +/- 0.01, 2.92 +/- 0.02]) = 2.98 +/- 0.01
+ Shell: BG measured inside and out
  + I (on axis): 2.69 +/- 0.02,
    + BG =  vmeane([2.75 +/- 0.02, 2.72 +/- 0.01]) = 2.726 +/- 0.01
  + II (to W): 2.69 +/- 0.01,
    + BG = vmeane([2.71 +/- 0.02, 2.72 +/- 0.02]) = 2.715 +/- 0.01
  + III (further to W): 2.64 +/- 0.02,
    + BG = vmeane([2.68 +/- 0.02, 2.67 +/- 0.02]) = 2.675 +/- 0.01
  + IV (to E): 2.74 +/- 0.02,
    + BG = vmeane([2.77 +/- 0.02, 2.76 +/- 0.02]) = 2.765 +/- 0.01

** Calculating the extinction

+ We can calculate a lower limit on the extinction by assuming that all the BG emission comes from behind the tadpole, so that A_{\lambda} = -2.5 log_{10} (B/BG)
  + This gives a value of A_{H\alpha }= 0.165 for the core, 0.09 for the head and 0.01 for the shell
+ Alternatively, we can find an upper limit by assuming that the core extinction is actually large (say 3), implying that 2.33/2.735 = 85% of the BG emission must come from in front of the tadpole.
  + This gives A_{H\alpha }= \infty for the core, 0.9 for the head, and 0.1 for the shell
| Region    | Bright        | mean BG        | -2.5 log(B/BG)  | -2.5 log(B'/BG') |
|-----------+---------------+----------------+-----------------+------------------|
| Core      | 2.35          | 2.735 +/- 0.02 | 0.165 +/- 0.008 | 3.266 +/- 0.054  |
| Head      | 2.52 +/- 0.03 | 2.735 +/- 0.02 | 0.089 +/- 0.015 | 0.822 +/- 0.180  |
| Tail I    | 2.64 +/- 0.02 | 2.78 +/- 0.02  | 0.056 +/- 0.011 | 0.405 +/- 0.085  |
| Tail II   | 2.84 +/- 0.03 | 2.98 +/- 0.01  | 0.052 +/- 0.012 | 0.263 +/- 0.066  |
| Shell I   | 2.69 +/- 0.02 | 2.726 +/- 0.01 | 0.014 +/- 0.009 | 0.103 +/- 0.066  |
| Shell II  | 2.69 +/- 0.01 | 2.715 +/- 0.01 | 0.010 +/- 0.006 | 0.073 +/- 0.041  |
| Shell III | 2.64 +/- 0.02 | 2.675 +/- 0.01 | 0.014 +/- 0.009 | 0.116 +/- 0.077  |
| Shell IV  | 2.74 +/- 0.02 | 2.765 +/- 0.01 | 0.010 +/- 0.009 | 0.064 +/- 0.059  |
#+TBLFM: $4=-2.5 log10($2/$3); f3::$5=-2.5 log10(($2 - 2.33)/($3 - 2.33)); f3


** Sizes
+ Head radius:
  + axis: 1.7 arcsec
  + side (east): 1.9 arcsec
  + side (west): 1.7 arcsec
+ Head thickness
  + 0.36 arcsec
+ Core size (diameter):
  + major axis (PA 50): 0.25 arcsec
  + minor axis: 0.12 arcsec
+ Shell radius:
  + axis: 6.9 arcsec
  + side (east): 5.3 arcsec
  + side (west): 5.9 arcsec
+ Shell thickness:
  + axis: 0.5 arcsec
  + side (west): 0.8 arcsec
  + side (east): 0.7 arcsec

** Density estimates
All assume D = 440 pc, sigma = 5e-22 cm^{2}/H

*** Core
+ Path length ~= 0.2 440 au = 1.312e15 cm
+ Minimum column
  + A = 0.165
  + N = 3.3e20 cm^{-2}
  + n = 2.5e5  cm^{-3}
+ Mass
  + assume area = pi (0.1 440 au)**2 = 1.36e30 cm^{2}
  + M = 1.36e30 3.3e20 mp /msun = 3.77e-7 M_{\odot}
+ Escape velocity
  + V = sqrt(2 G M / R) = 0.004 km/s
*** Head 
+ Path length ~= 2 (R h)  = 1.6 440 au = 1.05e16 cm
+ Minimum column
  + A = 0.09
  + N = 1.8e20 cm^{-2}
  + n = 17,000 cm^{-3}
+ Maximum column
  + A = 0.888
  + N = 1.776e21
  + n = 170,000 cm^{-3}
+ Mass 
  + assume area = pi (1.7 440 au)**2 = 3.93e32 cm^{2}
  + M = 3.93e32 1.8e20 mp / msun = 5.95e-5 M_{\odot} = 20 M_{\oplus}
+ Escape velocity
  + V = sqrt(2 G M / R) = 0.017 km/s
  + So certainly not self-gravitating
*** Shell
+ Path length ~= 2 (R h)^{1/2} = 3.7 440 au =2.435e16 cm
+ Minimum column
  + A = 0.012
  + N = 2.4e19 cm^{-2}
  + n = 1000 cm^{-3}
+ Maximum column
  + A = 0.1
  + N = 2e20 cm^{-2}
  + n = 8000 cm^{-3}

** Required ionizing flux if it is an ionized flow from head

*** Ionized density at head
+ Ionized density should be 1/40 of neutral density, assuming T = 1000 K and D-critical
  + Implies n = 425 cm^{-3}
  + Although this could be modified if magnetic support were important on the neutral side
+ On the other hand, shell is inconsistent with this:
  + Shell radius is 4 times head radius => geometric dilution of 16
  + Assume M = 3, means that shell density should be 16/3 = 5.3 times smaller than i-front density
  + Implying n = 5300 at ionization front
  + This could work if shock was still going into head
    + There would be a 2e5 cm^{-3} layer behind i-front, but if it were thin enough it wouldn't show up

*** Recombination limit
+ F = \alpha n^{2} h
+ \alpha = 2.6e-13 cm^{3}/s
+ n = 5300 cm^{-3}
+ h = 0.1 R = 75 AU = 1.12e15 cm
+ => F = 8.18e9 cm^{-2}
*** Advection limit
+ F = u n
+ u = c = 10 km/s
+ => F = 5.3e9 cm^{-2}

** Required FUV flux if it is a neutral flow from head
+ The idea is that the head and core will be molecular with T = 30-50 K
+ Then the gas is dissociated, lowering its density and flowing out in a neutral photoevaporation flow with T ~ 300 K
  + This will have lower density, but the jump may be signifcantly less than 40 since the molecular gas is likely to be magnetically dominated
  + Assuming Alfven speed of V_{A} \approx 1 km/s
*** Neutral density at the head
+ Sound speed: c = sqrt(k T / m) = 1.4 km/s T_{300}^{1/2} for neutral gas (m = 1.3 mp)
  + For molecular gas @ 30 K: c = 0.3 km/s
+ D-type transonic dissociation front will have P_{m} = 2 P_{n}
+ Assume P_{m} is dominated by magnetic pressure:  P_{m} = 0.5 \rho_{m} V_{A}^{2} = 2 \rho_{n} c_{n}^{2}
  + =>  \rho_{n} / \rho_{m} =  0.25 (V_{A} / c_{n})^{2} = 0.128 V_{1}^{2} / T_{300}
  + where V_{1} is molecular Alfven speed in units of 1 km/s
+ Since we have n_{m} = 1.7e4 pcc (this is H nucleon density) this implies:
  + n_{n} = 2200 V_{1}^{2} / T_{300} pcc
+ This is more or less consistent with the shell density of 1000 pcc
  + which implies n_{n} = (1000 16) / M_{sh} = 5300 M_{3}^{-1} pcc
  + [ ] so long as neutral flow is isothermal (need to check heating timescale)
+ So it would work with V_{A,m} = 1.7 km/s and T_{n} = 300 K or similar combination
  + Implies \beta_{m} = 2 c^{2} / V_{A}^{2} = 0.06
  + [ ] Would this cause anisotropic compression?
  + In neutral gas, B would be smaller or equal to strength in molecular gas
    + equal in the case of B perp to front
    + so neutral V_{A} goes down by sqrt of density jump => V_{A} < 0.95 km/s
    + => \beta_{n} > 4.3, so neutral gas is thermally dominated but not by much
*** Advection limit for dissociation
+ F = 0.5 u n / f_{d}
+ u = c = 1.4  T_{300}^{1/2} km/s
+ n = 5300 pcc
+ f_{d} \approx 0.1 (dissociation fraction for Solomon process)
+ => F = 3.71e9 phot/cm^{2}
+ Habing Flux is 1.213e7
+ So G/G_{0} \approx 300
+ And G/n = 0.02 - is this big or small?
  + Seems to be small - see next item
+ Main IF in Orion has
  + G = 2.5e13 => G/G_{0} = 2e6
  + n < 1e6 certainly, so G/n \sim 1
**** And what would column of neutral flow be?
+ Column \approx n_{0} r_{0}
  + Is this still true for accelerated flows?
+ With n_{0} = 5300 pcc and r_{0} = 1.12e16 cm
+ => N = 5.936e19 cm, or A_{V} = 0.03
+ [ ] Is it feasible to have the heating/dissociation front at such a low column?

*** And what if the shell corresponded to an ionization front?
+ Or more exactly, the neutral shell behind the i-front
+ Neutral density in shell: n = 1000 pcc
+ Again assume D-critical transition
  + P_{n} = 2 P_{i} where this time they are both thermally dominated
    + P_{n} = \rho_{n} c_{n}^{2} and  P_{i} = \rho_{i} c_{i}^{2} with c_{n} \approx 1.4 km/s, c_{i} \approx 10 km/s
    + => n_{i} = 0.01 n_{n} = 10 pcc - that is very low!
  + That would mean an advective flux of  c_{i} n_{i} = 1e7 /cm^{2}/s
  + Recombination flux of 0.1 R \alpha n^{2}
    + R = 7 arcsec = 4.6e16 cm
    + => F = 1.2e5 /cm^{2}/s
    + which is completely negligible
  + This implies a low luminosity for the ionizing star
    + With no attenuation @1.32e19 cm: QH = 2.2e46

*** How can the shell-as-i-front scenario be salvaged?

**** Smaller density jump across the i-front
+ This would require either:
  1) magnetic support in the neutral shell, or
  2) higher T in the neutral shell
**** Large attenuation of ionizing radiation by recombinations in HII region
+ Ratio of 

** Illuminating star?
These are the only ones in the right direction:
| Star        |   HIP | RA                | Dec               | Sp T  |     \Delta\alpha |      \Delta\delta |      D |   PA |
|-------------+-------+-------------------+-------------------+-------+--------+---------+--------+------|
| Globule     |       | 5@ 34' 57.199"    | -5@ 23' 37.49"    |       |    0.0 |     0.0 |    0.0 |  0e0 |
|-------------+-------+-------------------+-------------------+-------+--------+---------+--------+------|
| HD 36939    |       | 5@ 34' 55.265"    | -5@ 30' 23.40"    | B9V   |  -28.9 |  -405.9 |  406.9 | 184. |
| HD 36917    |       | 05@ 34' 46.984"   | -05@ 34' 14.59"   | A0V   | -152.5 |  -637.1 |  655.1 | 193. |
| iota Ori    | 26241 | 05@ 35' 25.982"   | -05@ 54' 35.64"   | O9III |  429.8 | -1858.2 | 1907.3 | 167. |
| ADS 4182 AB |       | 05@ 35' 02.68"    | -06@ 00' 07.2"    | B0    |   81.9 | -2189.7 | 2191.2 | 178. |
| HR 1887     | 26199 | 05@ 35' 02.68074" | -06@ 00' 07.3036" | B0.5V |   81.9 | -2189.8 | 2191.3 | 178. |
| HR 1886     | 26197 | 05@ 35' 01.00645" | -06@ 00' 33.3828" | B1v   |   56.9 | -2215.9 | 2216.6 | 179. |
#+TBLFM: $6=3600 * 15  * 0.995572228862 * deg($3 - @I$3) ;f1::$7=3600 deg($4 - @I$4);f1::$8=sqrt($6**2 + $7**2);f1::$9=arctan2($6, $7) % 360;f0

+ The first two do not seem promising at all.
  + At least, not for ionizing photons
    + Required flux is about 1e10 cm^{-2}
    + So at D = 430 arcsec = 2.83e18 cm, we need QH = 4 pi D**2 F = 1e48 phot/s
    + This is equivalent to a B0 star, not a B9 star
+ Iota Orionis looks more promising, except for the direction
  + There are some B0 stars as well
  + For ionizing photons, it is still too faint
    + D = 2000 arcsec = 1.32e19 cm (4.27 pc)
    + => required ionizing luminosity: 2.2e49 phot/s
    + I think this is more than a O9III star could provide
    + *No it is not!* 2e49 is spot on
  + For FUV photons, required flux is 3.71e9
    + => FUV photon luminosity of 8e48
    + Could be larger if real distance is larger than projected distance.
*** Table of stellar parameters
+ From Hohle et al (2010) 2010AN....331..349H
+ Surface gravity is calculated as g = G M / R^{2} = G M 4 \pi \sigma T^{4} / L
+ Luminosity and mass for \iota Ori B are my guesses
| name    |   HIP | Sp T   |  Teff | L_{bol} / L_{\odot} | M / M_{\odot}          | log g         |
|---------+-------+--------+-------+-----------+-----------------+---------------|
| \iota Ori   | 26241 | O9 III | 32000 |    5.29e5 | 32.74 +/- 13.89 | 3.21 +/- 0.18 |
| \iota Ori B |       | B1V    | 24000 |     37000 | 15              | 3.52          |
| HR 1886 | 26197 | B1 V   | 25400 |     37459 | 15.00 +/- 0.45  | 3.62 +/- 0.01 |
| HR 1887 | 26199 | B0.5 V | 27700 |     37663 | 15.66 +/- 0.5   | 3.78 +/- 0.01 |
#+TBLFM: $7=log10($Grav $6 $Msun 4 $pi $sigma $4**4 / $5 $Lsun) ; f2

*** Another table of stellar parameters for the \iota Ori binary

From \cite{Stickland:1987a}
+ They find E(B - V) \approx 0.03 => A_{V} \approx 0.1 mag
+ And use a distance modulus of \mu = 8.52 +/- 0.17
  + Corresponding to distance of 10**(0.2 (8.52 +/- 0.17) + 1) = 506 +/- 40 pc
  + So if the distance were really 400 +/- 100 pc, we would have \mu = 8.01 +/- 0.54
  + Or, using (436 +/- 20) - (4 +/- 4) = 432 +/- 20.4
    + Coming from the O'Dell & Henney (2008) recommendation together with assuming that \Delta z \sim \Delta r for the \iota--\theta^{1} distance
    + which implies that \mu = 8.18 +/- 0.10, which gives a correction of 0.34 +/- 0.10 to the absolute magnitudes
  + This would reduce the bolometric luminosities a tad wrt to the Stickland values, which is included in the following table: 
+ Relationship between absolute magnitude and luminosity:
  + log_{10} L/L_{\odot}  = -0.4 (M_{bol} - M_{bol,\odot}),
  + where M_{bol,\odot} = (+4.862 +/- 0.02) + (-0.107+-0.02) = 4.735 +/- 0.02
    + Pecaut & Mamajek (2013)
    + [[https://sites.google.com/site/mamajeksstarnotes/basic-astronomical-data-for-the-sun][mamajeksstarnotes/basic-astronomical-data-for-the-sun]]
  + Alternatively, IAU Commissions 25 and 36 simply define a zero point for the absolute magnitude scale of L_{0} = 3.055e28 W = 3.055e35 erg/s = 79.974 L_{\odot}
    + This means that L = L_{0} 10^{-0.4 M}
+ Calculation of Radii:
  + 4 \pi R^{2} \sigma T^{4} = L => =$R = sqrt( $L / 4 $pi $sigma $T**4)=
  + We include a 5% uncertanty in T_{eff} measurement
+ Masses are from binary orbit solution of Strickland
+ Gravity is then just G M / R^{2}

| name    | Sp T   |  Teff | M_{bol}          | log L_{bol} / L_{\odot}   | R / R_{\odot}         | M / M_{\odot}       | log g         |
|---------+--------+-------+---------------+-----------------+----------------+--------------+---------------|
| \iota Ori   | O9 III | 32000 | -8.36 +/- 0.1 | 5.247 +/- 0.040 | 13.65 +/- 1.50 | 38.9 +/- 9.7 | 3.76 +/- 0.14 |
| \iota Ori B | B1 III | 21000 | -5.46 +/- 0.1 | 4.087 +/- 0.040 | 8.34 +/- 0.92  | 18.9 +/- 4.7 | 3.87 +/- 0.14 |
#+TBLFM: $5=log10(79.974) -0.4 $4 ; f3::$6=sqrt( 10**$5 $Lsun / 4 $pi $sigma $3**4 (1 +/- 0.05)**4) / $Rsun ; f2::$8=log10($Grav $7 $Msun / $6**2 $Rsun**2); f2::@2$4=-8.7 + 0.34 +/- 0.10::@3$4=-5.8  + 0.34 +/- 0.10

+ So the luminosity is significantly lower than before, by a factor of 3
+ I have saved the original versions in =stars/old/=
+ The new version has QH = 3.4e48, which is 5 times lower than before, unfortunately. 

*** Cloudy models of the stellar spectra
:PROPERTIES:
:dir:      stars
:tangle:   stars/generate-orion-seds.py
:END:

This is based on what I did for the [[id:7E209EE8-5EB0-49B8-82F1-99EBE7DC3446][Orion {N I} project]]

#+begin_src python
"""
Generate Cloudy input files for some OB stars in Orion
"""
#+end_src



**** Trapezium stars
#+begin_src python
stars = dict(
    th1C = dict(T=39000., g=4.1, L=5.31),
    th1A = dict(T=30000., g=4.0, L=4.45),
    th1D = dict(T=32000., g=4.2, L=4.47),
    th1B = dict(T=18000., g=4.1, L=3.25),
    th1C2 = dict(T=25000., g=3.86, L=4.2),
    )
#+end_src

**** NGC 1980 stars
#+begin_src python
stars.update(
    iota = dict(T=32000., g=3.76, L=5.25),
    iotaB = dict(T=21000., g=3.87, L=4.09),
    HR1886 = dict(T=25400., g=3.62, L=4.57),
    HR1887 = dict(T=27700., g=3.78, L=4.58),
)
#+end_src

**** Generate the cloudy input scripts
#+begin_src python
template = """\
title Spectrum of Orion star %(id)s using Tlusty
table star tlusty OBstar 3-dim %(T)i g=%(g).2f z=-0.1
luminosity total solar %(L).2f 
hden 4
radius 17
stop zone 1
save continuum file="%(id)s.cont"
"""

for star in stars:
    stars[star].update(id=star)
    with open(star + ".in", "w") as f:
        f.write(template % stars[star])


#+end_src


*** Download and compile the Tlusty atmosphere models
:PROPERTIES:
:dir:      ~/Work/CLOUDY/git-svn/data
:END:


**** Download models
Download http://nova.astro.umd.edu/Tlusty2002/database/obstar_merged_3d.ascii.gz (Note that it is big - 86MB)
**** Unpack models
#+BEGIN_SRC sh
mv ~/Downloads/obstar_merged_3d.ascii .
#+END_SRC

#+RESULTS:

**** Compile models
#+BEGIN_SRC sh :results verbatim
echo "compile stars" | ../source/cloudy.exe 
#+END_SRC

#+RESULTS:
#+begin_example
                                                         Cloudy 13.01.01
                                                         www.nublado.org

                       **************************************13Jan01**************************************
                       *                                                                                 *
                       * compile stars                                                                   *
 AtlasCompile on the job.
 CoStarCompile on the job.
 Kurucz79Compile on the job.
 MihalasCompile on the job.
 RauchCompile on the job.
 StarburstCompile on the job.
 TlustyCompile on the job.
 WernerCompile on the job.
 WMBASICCompile on the job.

 1 ascii file(s) found, 1 file(s) up to date.

 The compilation was successful!
 The portable ascii files are no longer needed and may be deleted to save space.

 Good Luck!!


 [Stop in ParseCompile at parse_compile.cpp:507, Cloudy exited OK]
#+end_example

**** Check models are there
#+BEGIN_SRC sh :results output 
echo "table star available" | ../source/cloudy.exe 
#+END_SRC

#+RESULTS:
#+begin_example
                                                         Cloudy 13.01.01
                                                         www.nublado.org

                       **************************************13Jan01**************************************
                       *                                                                                 *
                       * table star available                                                            *

 I will now list all stellar atmosphere grids that are ready to be used (if any).
 User-defined stellar atmosphere grids will not be included in this list.

   table star tlusty OBstar 3-dim <Teff> <log(g)> <log(Z)>
 [Stop in ParseTable at parse_table.cpp:1273, Cloudy exited OK]
#+end_example

*** Makefile to run the cloudy jobs
	:PROPERTIES:
        :tangle:   stars/Makefile
	:END:
#+begin_src makefile
CLOUDY=cloudy.exe
SRC = $(wildcard *.in)
OBJ = $(SRC:.in=.out)

all: $(OBJ)

%.out: %.in
	$(CLOUDY) < $< > $@ 
#+end_src

*** Regenerate input files and run make
:PROPERTIES:
:dir:      stars
:END:

#+begin_src sh :results output
python ./generate-orion-seds.py
export PATH=$PATH:~/Work/CLOUDY/git-svn/source
make -j 6 
#+end_src

#+RESULTS:
: cloudy.exe < HR1886.in > HR1886.out
: cloudy.exe < HR1887.in > HR1887.out
: cloudy.exe < iota.in > iota.out
: cloudy.exe < iotaB.in > iotaB.out
: cloudy.exe < th1A.in > th1A.out
: cloudy.exe < th1B.in > th1B.out
: cloudy.exe < th1C.in > th1C.out
: cloudy.exe < th1C2.in > th1C2.out
: cloudy.exe < th1D.in > th1D.out


*** Original copy of Iota Ori parameters
+ HIP	 26241	 	Hipparcos identification number
+ Magnitudes
  + B = 2.53
  + V = 2.77
  + J = 3.490 +/- 0.304
  + H = 3.648 +/- 0.252
  + K = 3.752 +/- 0.252
+ plx = 1.40 +/- 0.22 mas => D = 714.285714286 +/- 112.244897959 pc
+ SpType	O9 III
+ Teff	 32000	K
+ M = 32.74 +/- 13.89 M_{\odot}
+ L = 5.29e5 L_{\odot}
+ Secondary:
  + B1V
  + Teff 24000 K
  + L unknown - but will be 30% of primary if they have the same radius


*** Stromgren sphere around \iota Ori
+ QH = 2e49
+ R > 4 pc
+ Q_{H} = 4/3 pi R^{3} n^{2} \alpha
+ => n = sqrt( Q_{H} / 4/3 pi R^{3} \alpha) = 100 R_{4}^{-3/2} pcc


** Vizier acknowledgments
This research has made use of the VizieR catalogue access tool, CDS, Strasbourg, France. The original description of the VizieR service was published in A&AS 143, 23
* COMMENT Export options
#+TITLE: Shadow Disks
#+AUTHOR: William Henney
#+EMAIL: w.henney@crya.unam.mx
#+OPTIONS: ':nil *:t -:t ::t <:t H:5 \n:nil ^:{} arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not LOGBOOK) date:t e:t
#+OPTIONS: email:nil f:t inline:t num:nil p:nil pri:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+CREATOR: Emacs 24.3.1 (Org mode 8.0.7)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="wjh-org.css" />

# Local Variables:
# org-src-preserve-indentation: t
# End:








